<a href="https://colab.research.google.com/github/sadmaaan/Practice-Public-Dataset-ML/blob/main/email_spam_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [129]:
import numpy as np
import pandas as pd

In [92]:
df = pd.read_csv("emails.csv")
df = df.iloc[:,0:2]

In [93]:
df.head(3)

text spam
0  Subject: naturally irresistible your corporate...    1
1  Subject: the stock trading gunslinger  fanny i...    1
2  Subject: unbelievable new homes made easy  im ...    1

In [94]:
df.dropna(inplace=True)

In [95]:
df.isnull().sum()

text    0
spam    0
dtype: int64

In [96]:
df.drop_duplicates(inplace=True)
df = df.reset_index(drop=True)
df.head(5)

text spam
0  Subject: naturally irresistible your corporate...    1
1  Subject: the stock trading gunslinger  fanny i...    1
2  Subject: unbelievable new homes made easy  im ...    1
3  Subject: 4 color printing special  request add...    1
4  Subject: do not have money , get software cds ...    1

In [97]:
df['spam'].value_counts()

0                                                                                               4326
1                                                                                               1367
 mr suresh prabhu                                                                                  1
 its termination would not  have such a phenomenal impact on the power situation .  however        1
Name: spam, dtype: int64

In [98]:
# Filter rows based on column values

spam_temp = []

for i in df.spam:
  if i=='0' or i=='1':
    spam_temp.append(True)
  else:
    spam_temp.append(False)


In [99]:
print(spam_temp)

[True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, Tru

In [100]:
len(spam_temp)

5695

In [101]:
spam_series = pd.Series(spam_temp)
spam_series.head()

0    True
1    True
2    True
3    True
4    True
dtype: bool

In [102]:
df = df[spam_series]

In [ ]:
df['spam'].value_counts()

0    4326
1    1367
Name: spam, dtype: int64

# Train test split

In [103]:
X = df.text.values
y = df.spam.values

In [104]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

### Data prepossessing

In [105]:
from sklearn.feature_extraction.text import CountVectorizer

In [106]:
cv = CountVectorizer()
X_train = cv.fit_transform(X_train)

In [108]:
X_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

## ML Algorithm

In [109]:
from sklearn.naive_bayes import MultinomialNB

In [110]:
model = MultinomialNB()
model.fit(X_train, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [111]:
X_test = cv.transform(X_test)

In [112]:
X_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [113]:
model.score(X_test, y_test)

0.9947322212467077

# Testing Manually

In [127]:
test_email = ["Hi, How are you?", "From: mrx.xyz.co.nz Mr.X want t0 know about your Email(*****): and Password:(******"]
test_email_t = cv.transform(test_email)
test_email_t.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [128]:
model.predict(test_email_t)

array(['0', '1'], dtype='<U1')